import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import { ThemeProvider } from "@/providers/theme-provider";
import { Toaster } from "sonner";
import "./globals.css";
import React from "react";
import TankQuerySetup from "@/components/tank-querysetup";
import UtilitiesProvider from "@/providers/UtilitiesProvider";

const mulish = Mulish({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mulish.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TankQuerySetup>
            <UtilitiesProvider>
              <Toaster />
              {children}
            </UtilitiesProvider>
          </TankQuerySetup>
        </ThemeProvider>
      </body>
    </html>
  );
}
