import { IoIosQuote } from "react-icons/io";
import { FaPhoneAlt } from "react-icons/fa";
import { IoMdPlayCircle } from "react-icons/io";

export const products: Product[] = [
  {
    name: "Blogs",
    description:
      "Insights, Ideas & latest feature launch: Your Go-To Hub for the Latest in Social",
    href: "#",
    icon: "description",
  },
  {
    name: "Events",
    description:
      "Learn, Engage, Excel: Your Gateway to know partners, team at CapCons",
    href: "#",
    icon: "editor_choice",
  },
  {
    name: "How-to videos",
    description: "Steps-by-Steps guide to community creation",
    href: "#",
    icon: "animated_images",
  },
  {
    name: "Stormnorms",
    description: "Contest that celebrates creators",
    href: "#",
    icon: IoIosQuote,
  },
];

export const callsToAction: CallToAction[] = [
  { name: "Book a demo", href: "#", icon: IoMdPlayCircle },
  { name: "Contact us", href: "#", icon: FaPhoneAlt },
];

export const TagsList = [
  "love",
  "instagood",
  "fashion",
  "photooftheday",
  "beautiful",
  "art",
  "photography",
  "happy",
  "cute",
  "tbt",
  "follow",
  "followme",
  "like4like",
  "picoftheday",
  "selfie",
  "summer",
  "friends",
  "instadaily",
  "repost",
  "nature",
  "girl",
  "fun",
  "style",
  "smile",
  "food",
];

export const MoviesTagList = [
  "love",
  "instagood",
  "fashion",
  "photooftheday",
  "beautiful",
  "art",
  "photography",
  "happy",
  "cute",
  "tbt",
  "follow",
  "followme",
  "like4like",
  "picoftheday",
  "selfie",
  "summer",
  "friends",
  "instadaily",
  "repost",
  "nature",
  "girl",
  "fun",
  "style",
  "smile",
  "food",
];

export const NewsTagLIst = [
  "love",
  "instagood",
  "fashion",
  "photooftheday",
  "beautiful",
  "art",
  "photography",
  "happy",
  "cute",
  "tbt",
  "follow",
  "followme",
  "like4like",
  "picoftheday",
  "selfie",
  "summer",
  "friends",
  "instadaily",
  "repost",
  "nature",
  "girl",
  "fun",
  "style",
  "smile",
  "food",
];

export const TechTagList = [
  "love",
  "instagood",
  "fashion",
  "photooftheday",
  "beautiful",
  "art",
  "photography",
  "happy",
  "cute",
  "tbt",
  "follow",
  "followme",
  "like4like",
  "picoftheday",
  "selfie",
  "summer",
  "friends",
  "instadaily",
  "repost",
  "nature",
  "girl",
  "fun",
  "style",
  "smile",
  "food",
];

export const GamingTagList = [
  "love",
  "instagood",
  "fashion",
  "photooftheday",
  "beautiful",
  "art",
  "photography",
  "happy",
  "cute",
  "tbt",
  "follow",
  "followme",
  "like4like",
  "picoftheday",
  "selfie",
  "summer",
  "friends",
  "instadaily",
  "repost",
  "nature",
  "girl",
  "fun",
  "style",
  "smile",
  "food",
];

export const HumorTagList = [
  "love",
  "instagood",
  "fashion",
  "photooftheday",
  "beautiful",
  "art",
  "photography",
  "happy",
  "cute",
  "tbt",
  "follow",
  "followme",
  "like4like",
  "picoftheday",
  "selfie",
  "summer",
  "friends",
  "instadaily",
  "repost",
  "nature",
  "girl",
  "fun",
  "style",
  "smile",
  "food",
];
