name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'  # Update this to Node.js 18.x or higher

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Deploy to Google Cloud Run
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: nextjs-app
        region: us-south2-c
        image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/nextjs-app
